---

- name: Update hostname in rc.conf(5)
  lineinfile:
    dest: /etc/rc.conf
    line: "hostname=\"{{ hostname_fqdn }}\""
    regexp: "^hostname="
    state: present
    validate: sh -n %s

- name: Update hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1    localhost {{ hostname_fqdn }}"
    regexp: "^127.0.0.1"
    state: present

- name: Update hostname (ipv6) in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "::1    localhost {{ hostname_fqdn }}"
    regexp: "^127.0.0.1"
    state: present
